backend:
  name: git-gateway
  repo: PireJoseph/synexcel
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "section-page"
    label: "Page Section"
    folder: "content/section-page"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Id", name: "id", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Ordre", name: "order", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Label image", name: "image_caption", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "single-page"
    label: "Page Additionnelle"
    folder: "content/single-page"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Id", name: "id", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Ordre", name: "order", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Label image", name: "image_caption", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
