backend:
  name: git-gateway
  repo: PireJoseph/synexcel
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "section"
    label: "Section"
    folder: "content/section"
    fields:
      - { label: "Id", name: "id", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Ordre", name: "order", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Label image", name: "image_caption", widget: "string" }

  - name: "section-page"
    label: "Page"
    folder: "content/section-page"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "string" }
      - {
          label: "Section",
          name: "section",
          widget: "relation",
          collection: "section",
          valueField: "id",
          displayFields: ["title"],
          searchFields: ["title"],
        }
      - { label: "Ordre", name: "order", widget: "number" }
      - { label: "Extrait", name: "excerpt", widget: "string" }
      - { label: "Créé le", name: "created", widget: "date" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Label image", name: "image_caption", widget: "string" }
      - { label: "Mis en avant", name: "featured", widget: "boolean" }
      - { label: "Body", name: "body", widget: "markdown" }
